package:
  name: versiontesting
  version: "2.4.8"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10

about:
  home: https://github.com/mcsloy/VersionTesting
  summary: "Something very insightful."
  license: MIT
