name: Build and Upload Conda Package

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      contents: write

    steps:
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: build-env
          miniconda-version: "latest"
          channels: conda-forge
          use-only-tar-bz2: false

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          # For semantic-versioning/release
          conda install conda-forge::python-semantic-release">9"
          # For building and publishing the anaconda package
          conda install -c conda-forge conda-build anaconda-client

      - name: Run semantic release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release version --no-commit

      - name: Build the Conda package
        run: conda build ./conda -c irl -c conda-forge

      - name: Upload the Conda package to Anaconda.org
        run: |
          PACKAGE_PATH=$(conda build ./conda --output)
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload $PACKAGE_PATH
