name: Build and Upload Conda Package

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: build-env
          miniconda-version: "latest"
          channels: conda-forge
          use-only-tar-bz2: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true

      - name: Install python-semantic-release for versioning
        run: |
          conda install conda-forge::python-semantic-release

      - name: Set version number
        run: |
          # Extract version from __init__.py and store in PACKAGE_VERSION
          PACKAGE_VERSION=$(semantic-release --noop version --print)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Install conda-build and anaconda-client
        run: |
          conda install -c conda-forge conda-build anaconda-client

      - name: Build the Conda package
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
        run: conda build ./conda -c irl -c conda-forge

      - name: Upload the Conda package to Anaconda.org
        run: |
          PACKAGE_PATH=$(conda build ./conda --output)
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload $PACKAGE_PATH
